# Homework 1

## Question 1
What's the version of Pandas that you installed?

You can get the version information using the __version__ field:

In [1]:
import pandas as pd

pd.__version__

'2.0.3'

### Getting the data
For this homework, we'll use the California Housing Prices dataset. Download it from here.

You can do it with wget:

In [2]:
!wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv

--2023-09-17 14:43:57--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.110.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1423529 (1.4M) [text/plain]
Saving to: ‘housing.csv’

housing.csv         100%[===================>]   1.36M  1.80MB/s    in 0.8s    

2023-09-17 14:43:58 (1.80 MB/s) - ‘housing.csv’ saved [1423529/1423529]



## Question 2
How many columns are in the dataset?

In [3]:
import pandas as pd

df = pd.read_csv("./housing.csv")

print("The total columns of the loaded dataframe is:", len(df.columns))

The total columns of the loaded dataframe is: 10


## Question 3
Which columns in the dataset have missing values?

In [10]:
df.isna().any()

longitude             False
latitude              False
housing_median_age    False
total_rooms           False
total_bedrooms         True
population            False
households            False
median_income         False
median_house_value    False
ocean_proximity       False
dtype: bool

The answer is `total_bedrooms`

## Question 4
How many unique values does the ocean_proximity column have?

In [11]:
df.nunique()

longitude               844
latitude                862
housing_median_age       52
total_rooms            5926
total_bedrooms         1923
population             3888
households             1815
median_income         12928
median_house_value     3842
ocean_proximity           5
dtype: int64

The answer is `5`

## Question 5
What's the average value of the median_house_value for the houses located near the bay?

In [23]:
mean_value = df[df['ocean_proximity'] == 'NEAR BAY']['median_house_value'].mean()

print("The average value of the median_house_value for the houses located near the bay is", mean_value)

The average value of the median_house_value for the houses located near the bay is 259212.31179039303


## Question 6
1. Calculate the average of total_bedrooms column in the dataset.
2. Use the fillna method to fill the missing values in total_bedrooms with the mean value from the previous step.
3. Now, calculate the average of total_bedrooms again.
4. Has it changed?

In [35]:
avg_total_bedroom = df['total_bedrooms'].mean()
print("Average before fillna: ", avg_total_bedroom)
avg_total_bedroom_after_fillna = df['total_bedrooms'].fillna(value=avg_total_bedroom).mean()
print("Average after fillna: ", avg_total_bedroom_after_fillna)

Average before fillna:  537.8705525375618
Average after fillna:  537.8705525375617


With the consideration of taking the only 3 digits after decimal point, the average value of total_bedrooms before and after `fillna` using mean **didn't changed**

## Question 7

1. Select all the options located on islands.
2. Select only columns `housing_median_age`, `total_rooms`, `total_bedrooms`.
3. Get the underlying NumPy array. Let's call it `X`.
4. Compute matrix-matrix multiplication between the transpose of `X` and `X`. To get the transpose, use `X.T`. Let's call the result `XTX`.
5. Compute the inverse of `XTX`.
6. Create an array `y` with values `[950, 1300, 800, 1000, 1300]`.
7. Multiply the inverse of `XTX` with the transpose of `X`, and then multiply the result by `y`. Call the result `w`.
8. What's the value of the last element of `w`?

In [37]:
df['ocean_proximity'].unique()

array(['NEAR BAY', '<1H OCEAN', 'INLAND', 'NEAR OCEAN', 'ISLAND'],
      dtype=object)

In [39]:
selected_cols = ['housing_median_age', 'total_rooms', 'total_bedrooms']

df_located_on_island = df[df['ocean_proximity'] == 'ISLAND']
df_selected_cols = df_located_on_island[selected_cols]
df_selected_cols

housing_median_age  total_rooms  total_bedrooms
8314                27.0       1675.0           521.0
8315                52.0       2359.0           591.0
8316                52.0       2127.0           512.0
8317                52.0        996.0           264.0
8318                29.0        716.0           214.0

In [47]:
X = df_selected_cols.to_numpy()
XT = X.T
XTX = XT.dot(X)
print("X value\n", X)
print("X transpose value\n", XT)
print("X time X transpose\n", XTX)

X value
 [[  27. 1675.  521.]
 [  52. 2359.  591.]
 [  52. 2127.  512.]
 [  52.  996.  264.]
 [  29.  716.  214.]]
X transpose value
 [[  27.   52.   52.   52.   29.]
 [1675. 2359. 2127.  996.  716.]
 [ 521.  591.  512.  264.  214.]]
X time X transpose
 [[9.6820000e+03 3.5105300e+05 9.1357000e+04]
 [3.5105300e+05 1.4399307e+07 3.7720360e+06]
 [9.1357000e+04 3.7720360e+06 9.9835800e+05]]


In [49]:
import numpy as np

inv_XTX = np.linalg.inv(XTX)
print("Inverse of XTX is\n", inv_XTX)

Inverse of XTX is
 [[ 9.19403586e-04 -3.66412216e-05  5.43072261e-05]
 [-3.66412216e-05  8.23303633e-06 -2.77534485e-05]
 [ 5.43072261e-05 -2.77534485e-05  1.00891325e-04]]


In [51]:
y = [950, 1300, 800, 1000, 1300]
w = inv_XTX.dot(XT).dot(y)
print("The value of last element in `w` is", w[-1])

The value of last element in `w` is 5.699229455065578
